### ISSUE TITLE
Unknown date type layer when run pretrained model

### ISSUE THREAD

**Issue by tamyle** [Seth-Park/MultimodalExplanations#3]
<img width="559" alt="screen shot 2018-12-21 at 3 53 37 pm" src="https://user-images.githubusercontent.com/28720287/50333728-d4eb2b00-0538-11e9-9b87-4bebaeba5b12.png">
Hi SethPark it was very nice of you to upload this folder but some errors happen and even how hard I try to do something with Makefile.config, this error did not pass and my teacher told me that my virtual machine did not have enough ram to run resnet152.

**Comment by Seth-Park** [comment]
Hi,

You will have to compile this version of Caffe: https://github.com/akirafukui/caffe/tree/feature/20160616_compact_bilinear

The error is occurring because the `SignedSqrt` layer is not supported in the standard Caffe branch.
