### ISSUE TITLE
EMD and Rank Correlation calculation

### ISSUE THREAD

**Issue by anshumanvenkatesh** [Seth-Park/MultimodalExplanations#5]
Does this repo contain code to calculate the Earth Mover Distance (EMD) and Rank Correlation as given in the paper? If not, how can I go about calculating them?

**Comment by Seth-Park** [comment]
This repo does not contain code for evaluating the attention maps.
We use the following packages to compute EMD and Rank Correlation:

EMD: https://github.com/wmayner/pyemd
Rank Correlation: https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.spearmanr.html

**Comment by anshumanvenkatesh** [comment]
Thank you!

**Comment by fariquelme** [comment]
Hello Seth,
I am using `pyemd` as you posted, but I have some doubts about the EMD calculation.
Did you use `emd` or `emd_samples` ?. 
If it is `emd`, what distance matrix did you use?, and if it is `emd_samples`, how many bins ?

Thanks!
