### ISSUE TITLE
Extracting visual explanations from VQA-X

### ISSUE THREAD

**Issue by anshumanvenkatesh** [Seth-Park/MultimodalExplanations#7]
I understand that the visual explanation (in the form of a heatmap) is given in VQA-X/visual. How do I extract the images? I am using the following numpy code:

```
img = np.load("11042002.npy")
shape = np.sort(img.shape)[::-1] # Reverse sorting shape so as to bring it in the form of (64x, 48x, 3)
plt.imshow(img.reshape(shape))
```

However, this leads to strange heatmaps like:

![11042002](https://user-images.githubusercontent.com/2269145/54712140-d1038080-4b08-11e9-94dc-08b9df1880ea.jpg)

What am I doing wrong here?

**Comment by Seth-Park** [comment]
Each file contains three heatmaps, so the loaded numpy array should have a shape of (3, x, y).
Indexing through the first axis of the loaded numpy array, you can access each heatmap and visualize it. The actual images you need to download from the VQA website. The heatmap is just a "mask" over the actual image.

**Comment by anshumanvenkatesh** [comment]
Thank you!

**Comment by anshumanvenkatesh** [comment]
A follow-up doubt:  For the paper's results, which of the three masks did you use for calculating the EMD and rank correlation?
